### ISSUE TITLE
forbidden？

### ISSUE THREAD

**Issue by miaomiao2970** [koishijs/koishi-plugin-enka#2]
[W] command enka 
                        Error: Forbidden
                            at [cordis.invoke] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\plugin-http\lib\index.cjs:334:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\plugin-http\lib\index.cjs:178:26)
                            at async _Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-enka\lib\index.js:148:27)
                            at async Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1078:14)
                            at async _Command.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1092:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2059:22
                            at async Proxy.withScope (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1968:22)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)

**Comment by Lipraty** [comment]
no more information. we testing no problems were found, consider whether this is due to too frequent visits or other issues.

**Comment by miaomiao2970** [comment]
> no more information. we testing no problems were found, consider whether this is due to too frequent visits or other issues.

我仅仅调用了这个指令一次（     日志里只有这一条报错诶

**Comment by Pisces-Moze** [comment]
我也一样
2025-02-02 12:52:16 [W] command enka 魈
                        Error: Forbidden
                            at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:340:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:178:26)
                            at async _Command.<anonymous> (/koishi/node_modules/koishi-plugin-enka/lib/index.js:148:27)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1083:14)
                            at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1097:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2066:22
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:1975:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)

**Comment by Lipraty** [comment]
To check if your access is restricted, try reaching [Enka](https://enka.network) using the same network connection/IP address as your automated bot. If you can't connect through this method, it likely indicates your account or IP has been blocked.

**Comment by Lipraty** [comment]
fixed of 80a9127823e6c3d75fb88a20991bc6bb0c7bb00b. you can update to `1.4.3`
